### ISSUE TITLE
Add support for Python 3.10

### ISSUE THREAD

**Issue by akihironitta** [Borda/pyDeprecate#18]
## 🚀 Feature
I believe `pyDeprecate` supports Python 3.10 already, but it'd be nice to see its version badge explicitly on https://pypi.org/projects/pyDeprecate.

<img width="187" alt="Screen Shot 2022-04-27 at 10 57 00" src="https://user-images.githubusercontent.com/20610905/165422964-98009846-0618-4378-a5db-0ada38657148.png">

### Additional context
Found during the survey for https://github.com/PyTorchLightning/pytorch-lightning/issues/9980.

**Comment by Borda** [comment]
yep, mind sending a PR? :)

**Comment by akihironitta** [comment]
@Borda Just realised that `setup.py` has already been updated to support 3.10! https://github.com/Borda/pyDeprecate/blob/main/setup.py

It's just that the latest release (`v0.3.2`) doesn't include the change, so publishing a new one (`v0.3.3`) should suffice, I believe?

**Comment by Borda** [comment]
> doesn't include the change, so publishing a new one (v0.3.3) should suffice, I believe?

true, but this is just nice to have; it does not have any functional limitations, correct?
I am in the process (thinking) to have the next v0.4, which would eventually insert also text to docs...
